if(WITH_PYTHON)
    find_package(Python3 COMPONENTS Interpreter Development)
    find_package(pybind11 CONFIG)

    if(pybind11_FOUND)
        pybind11_add_module(SBoPy MODULE Python.cpp)
        target_link_libraries(SBoPy PUBLIC GSL::gsl Boost::boost fmt::fmt ${OPTIONAL_LIBS})
    else()
        set(WITH_PYTHON OFF)
    endif()
endif()
